# Generated by Django 3.1.1 on 2020-11-05 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pcbcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Essence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('component', models.CharField(blank=True, choices=[('CPU', (('CPU_title', 'CPU title'), ('CPU_brand', 'CPU brand'), ('CPU_cores', 'CPU cores'), ('CPU_threads', 'CPU threads'), ('CPU_frequency', 'CPU frequency'), ('CPU_socket', 'CPU socket'), ('CPU_value', 'CPU value'), ('CPU_price', 'CPU price'))), ('GPU', (('GPU_title', 'GPU title'), ('GPU_brand', 'GPU brand'), ('GPU_memory', 'GPU memory'), ('GPU_value', 'GPU value'), ('GPU_price', 'GPU price'))), ('MotherBoard', (('MotherBoard_title', 'MotherBoard title'), ('MotherBoard_brand', 'MotherBoard brand'), ('MotherBoard_chipset', 'MotherBoard chipset'), ('MotherBoard_socket', 'MotherBoard socket'), ('MotherBoard_value', 'MotherBoard value'), ('MotherBoard_price', 'MotherBoard price'))), ('RAM', (('RAM_title', 'RAM title'), ('RAM_brand', 'RAM brand'), ('RAM_frequency', 'RAM frequency'), ('RAM_size', 'RAM size'), ('RAM_value', 'RAM value'), ('RAM_price', 'RAM price'))), ('HDD', (('HDD_title', 'HDD title'), ('HDD_brand', 'HDD brand'), ('HDD_type', 'HDD type'), ('HDD_read', 'HDD read'), ('HDD_write', 'HDD write'), ('HDD_size', 'HDD size'), ('HDD_value', 'HDD value'), ('HDD_price', 'HDD price'))), ('SSD', (('SSD_title', 'SSD title'), ('SSD_brand', 'SSD brand'), ('SSD_type', 'SSD type'), ('SSD_read', 'SSD read'), ('SSD_write', 'SSD write'), ('SSD_size', 'SSD size'), ('SSD_value', 'SSD value'), ('SSD_price', 'SSD price'))), ('PowerSupply', (('PowerSupply_title', 'PowerSupply title'), ('PowerSupply_brand', 'PowerSupply brand'), ('PowerSupply_power', 'PowerSupply power'), ('PowerSupply_value', 'PowerSupply value'), ('PowerSupply_price', 'PowerSupply price'))), ('Other', (('Other_budget', 'Budget'), ('Other_os', 'OS')))], max_length=20, null=True)),
                ('next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbknowledge.question')),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.IntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbknowledge.component')),
                ('essence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbknowledge.essence')),
            ],
        ),
        migrations.AddField(
            model_name='essence',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_question', to='pcbknowledge.question'),
        ),
        migrations.AddField(
            model_name='essence',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbknowledge.question'),
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('cpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbcore.cpu')),
                ('gpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbcore.gpu')),
                ('motherboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbcore.motherboard')),
                ('powersupply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbcore.powersupply')),
                ('ram', models.ManyToManyField(to='pcbcore.RAM')),
                ('rom', models.ManyToManyField(to='pcbcore.ROM')),
            ],
        ),
    ]
