# Generated by Django 3.1.1 on 2020-10-29 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pcbcore', '0002_rom_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('cpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbcore.cpu')),
                ('gpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbcore.gpu')),
                ('motherboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbcore.motherboard')),
                ('powersupply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbcore.powersupply')),
                ('ram', models.ManyToManyField(to='pcbcore.RAM')),
                ('rom', models.ManyToManyField(to='pcbcore.ROM')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Essence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('build', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbknowledge.build')),
                ('next', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbknowledge.question')),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.IntegerField()),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pcbknowledge.component')),
                ('essence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pcbknowledge.essence')),
            ],
        ),
        migrations.AddField(
            model_name='essence',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbknowledge.question'),
        ),
    ]
