# Generated by Django 3.1.1 on 2020-11-12 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pcbcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Essence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('component', models.CharField(blank=True, choices=[('CPU', (('CPU_model', 'CPU model'), ('CPU_brand', 'CPU brand'), ('CPU_cores', 'CPU cores'), ('CPU_threads', 'CPU threads'), ('CPU_socket', 'CPU socket'), ('CPU_benchmark', 'CPU benchmark'), ('CPU_frequency', 'CPU frequency'), ('CPU_price', 'CPU price'))), ('GPU', (('GPU_model', 'GPU model'), ('GPU_brand', 'GPU brand'), ('GPU_memory', 'GPU memory'), ('GPU_benchmark', 'GPU benchmark'), ('GPU_price', 'GPU price'))), ('MotherBoard', (('MotherBoard_model', 'MotherBoard model'), ('MotherBoard_brand', 'MotherBoard brand'), ('MotherBoard_formfactor', 'MotherBoard formfactor'), ('MotherBoard_chipset', 'MotherBoard chipset'), ('MotherBoard_socket', 'MotherBoard socket'), ('MotherBoard_year', 'MotherBoard year'), ('MotherBoard_price', 'MotherBoard price'))), ('RAM', (('RAM_model', 'RAM model'), ('RAM_brand', 'RAM brand'), ('RAM_type', 'RAM type'), ('RAM_frequency', 'RAM frequency'), ('RAM_capacity', 'RAM capacity'), ('RAM_count', 'RAM count'), ('RAM_benchmark', 'RAM benchmark'), ('RAM_price', 'RAM price'))), ('HDD', (('HDD_model', 'HDD model'), ('HDD_brand', 'HDD brand'), ('HDD_benchmark', 'HDD benchmark'), ('HDD_formfactor', 'HDD formfactor'), ('HDD_capacity', 'HDD capacity'), ('HDD_price', 'HDD price'))), ('SSD', (('SSD_model', 'SSD model'), ('SSD_brand', 'SSD brand'), ('SSD_benchmark', 'SSD benchmark'), ('SSD_formfactor', 'SSD formfactor'), ('SSD_capacity', 'SSD capacity'), ('SSD_price', 'SSD price'))), ('PowerSupply', (('PowerSupply_model', 'PowerSupply model'), ('PowerSupply_brand', 'PowerSupply brand'), ('PowerSupply_power', 'PowerSupply power'), ('PowerSupply_value', 'PowerSupply value'), ('PowerSupply_price', 'PowerSupply price'))), ('Other', (('Other_budget', 'Budget'), ('Other_os', 'OS')))], max_length=32, null=True)),
                ('next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbknowledge.question')),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.IntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbknowledge.component')),
                ('essence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='pcbknowledge.essence')),
            ],
        ),
        migrations.AddField(
            model_name='essence',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_question', to='pcbknowledge.question'),
        ),
        migrations.AddField(
            model_name='essence',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essences', to='pcbknowledge.question'),
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('cpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbcore.cpu')),
                ('gpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbcore.gpu')),
                ('hdd', models.ManyToManyField(to='pcbcore.HDD')),
                ('motherboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbcore.motherboard')),
                ('powersupply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbcore.powersupply')),
                ('ram', models.ManyToManyField(to='pcbcore.RAM')),
                ('ssd', models.ManyToManyField(to='pcbcore.SSD')),
            ],
        ),
    ]
