# Generated by Django 3.1.1 on 2020-10-29 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcbknowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbknowledge.component'),
        ),
    ]
