# Generated by Django 3.1.3 on 2020-12-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbknowledge', '0002_question_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('type', models.CharField(blank=True, choices=[('i', 'int'), ('f', 'float'), ('s', 'string')], max_length=1, null=True)),
            ],
        ),
    ]
