# Generated by Django 3.1.1 on 2020-10-29 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcbknowledge', '0003_auto_20201029_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='build',
        ),
        migrations.AddField(
            model_name='essence',
            name='next_question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_question', to='pcbknowledge.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='component',
            field=models.CharField(blank=True, choices=[('CPU', (('CPU_title', 'CPU title'), ('CPU_brand', 'CPU brand'), ('CPU_cores', 'CPU cores'), ('CPU_threads', 'CPU threads'), ('CPU_frequency', 'CPU frequency'), ('CPU_socket', 'CPU socket'), ('CPU_value', 'CPU value'), ('CPU_price', 'CPU price'))), ('GPU', (('GPU_title', 'GPU title'), ('GPU_brand', 'GPU brand'), ('GPU_memory', 'GPU memory'), ('GPU_value', 'GPU value'), ('GPU_price', 'GPU price'))), ('MotherBoard', (('MotherBoard_title', 'MotherBoard title'), ('MotherBoard_brand', 'MotherBoard brand'), ('MotherBoard_chipset', 'MotherBoard chipset'), ('MotherBoard_socket', 'MotherBoard socket'), ('MotherBoard_value', 'MotherBoard value'), ('MotherBoard_price', 'MotherBoard price'))), ('RAM', (('RAM_title', 'RAM title'), ('RAM_brand', 'RAM brand'), ('RAM_frequency', 'RAM frequency'), ('RAM_size', 'RAM size'), ('RAM_value', 'RAM value'), ('RAM_price', 'RAM price'))), ('ROM', (('ROM_title', 'ROM title'), ('ROM_brand', 'ROM brand'), ('ROM_type', 'ROM type'), ('ROM_read', 'ROM read'), ('ROM_write', 'ROM write'), ('ROM_size', 'ROM size'), ('ROM_value', 'ROM value'), ('ROM_price', 'ROM price'))), ('PowerSupply', (('PowerSupply_title', 'PowerSupply title'), ('PowerSupply_brand', 'PowerSupply brand'), ('PowerSupply_power', 'PowerSupply power'), ('PowerSupply_value', 'PowerSupply value'), ('PowerSupply_price', 'PowerSupply price')))], max_length=20, null=True),
        ),
    ]
