# Generated by Django 3.1.3 on 2020-12-13 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcbknowledge', '0003_componentvariable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='component',
        ),
        migrations.AddField(
            model_name='question',
            name='component_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbknowledge.componentvariable'),
        ),
    ]
