# Generated by Django 3.1.3 on 2020-12-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbknowledge', '0005_auto_20201213_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentvariable',
            name='component',
            field=models.CharField(blank=True, choices=[('CPU', 'CPU'), ('GPU', 'GPU'), ('RAM', 'RAM'), ('MB', 'MotherBoard'), ('SSD', 'SSD'), ('HDD', 'HDD'), ('PS', 'PowerSupply')], max_length=3, null=True),
        ),
    ]
