# Generated by Django 3.1.3 on 2020-12-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbknowledge', '0006_componentvariable_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentvariable',
            name='component',
            field=models.CharField(choices=[('CPU', 'CPU'), ('GPU', 'GPU'), ('RAM', 'RAM'), ('MB', 'MotherBoard'), ('SSD', 'SSD'), ('HDD', 'HDD'), ('PS', 'PowerSupply')], max_length=3),
        ),
        migrations.AlterField(
            model_name='componentvariable',
            name='type',
            field=models.CharField(choices=[('i', 'int'), ('f', 'float'), ('s', 'string')], max_length=1),
        ),
    ]
