# Generated by Django 3.1.3 on 2020-12-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbknowledge', '0007_auto_20201213_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentvariable',
            name='component',
            field=models.CharField(choices=[('CPU', (('CPU_model', 'CPU model'), ('CPU_brand', 'CPU brand'), ('CPU_cores', 'CPU cores'), ('CPU_threads', 'CPU threads'), ('CPU_frequency', 'CPU frequency'), ('CPU_socket', 'CPU socket'), ('CPU_benchmark', 'CPU benchmark'), ('CPU_frequency', 'CPU frequency'), ('CPU_price', 'CPU price'))), ('GPU', (('GPU_model', 'GPU model'), ('GPU_brand', 'GPU brand'), ('GPU_memory', 'GPU memory'), ('GPU_benchmark', 'GPU benchmark'), ('GPU_price', 'GPU price'))), ('RAM', (('RAM_model', 'RAM model'), ('RAM_brand', 'RAM brand'), ('RAM_type', 'RAM type'), ('RAM_frequency', 'RAM frequency'), ('RAM_capacity', 'RAM capacity'), ('RAM_count', 'RAM count'), ('RAM_benchmark', 'RAM benchmark'), ('RAM_price', 'RAM price'))), ('MB', (('MotherBoard_model', 'MotherBoard model'), ('MotherBoard_brand', 'MotherBoard brand'), ('MotherBoard_formfactor', 'MotherBoard formfactor'), ('MotherBoard_chipset', 'MotherBoard chipset'), ('MotherBoard_socket', 'MotherBoard socket'), ('MotherBoard_year', 'MotherBoard year'), ('MotherBoard_price', 'MotherBoard price'))), ('SSD', (('SSD_model', 'SSD model'), ('SSD_brand', 'SSD brand'), ('SSD_benchmark', 'SSD benchmark'), ('SSD_formfactor', 'SSD formfactor'), ('SSD_capacity', 'SSD capacity'), ('SSD_price', 'SSD price'))), ('HDD', (('HDD_model', 'HDD model'), ('HDD_brand', 'HDD brand'), ('HDD_benchmark', 'HDD benchmark'), ('HDD_formfactor', 'HDD formfactor'), ('HDD_capacity', 'HDD capacity'), ('HDD_price', 'HDD price'))), ('PS', (('PowerSupply_model', 'PowerSupply model'), ('PowerSupply_brand', 'PowerSupply brand'), ('PowerSupply_power', 'PowerSupply power'), ('PowerSupply_value', 'PowerSupply value'), ('PowerSupply_price', 'PowerSupply price'))), ('Other', (('Other_budget', 'Budget'), ('Other_os', 'OS')))], max_length=32),
        ),
    ]
