# Generated by Django 3.1.3 on 2020-12-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbknowledge', '0008_auto_20201213_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentvariable',
            name='type',
            field=models.CharField(choices=[('int', 'int'), ('float', 'float'), ('string', 'string')], max_length=6),
        ),
    ]
