# Generated by Django 3.1.3 on 2020-12-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbknowledge', '0009_auto_20201213_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_first',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
