# Generated by Django 3.1.3 on 2020-12-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbknowledge', '0010_question_is_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentvariable',
            name='type',
            field=models.CharField(choices=[('int', 'int'), ('float', 'float'), ('string', 'string'), ('bool', 'bool')], max_length=6),
        ),
    ]
