# Generated by Django 3.1.3 on 2020-12-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbknowledge', '0011_auto_20201216_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='os',
            field=models.BooleanField(default=False),
        ),
    ]
