# Generated by Django 3.1.3 on 2020-12-16 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcbcore', '0004_auto_20201216_1251'),
        ('pcbknowledge', '0014_auto_20201216_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='hdd',
        ),
        migrations.AddField(
            model_name='build',
            name='hdd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbcore.hdd'),
        ),
        migrations.RemoveField(
            model_name='build',
            name='ram',
        ),
        migrations.AddField(
            model_name='build',
            name='ram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbcore.ram'),
        ),
        migrations.RemoveField(
            model_name='build',
            name='ssd',
        ),
        migrations.AddField(
            model_name='build',
            name='ssd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcbcore.ssd'),
        ),
    ]
