# Generated by Django 3.1.1 on 2020-10-13 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chipset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ROM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('read', models.IntegerField()),
                ('write', models.IntegerField()),
                ('size', models.IntegerField()),
                ('value', models.IntegerField()),
                ('price', models.IntegerField()),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('frequency', models.FloatField()),
                ('size', models.IntegerField()),
                ('value', models.IntegerField()),
                ('price', models.IntegerField()),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('power', models.IntegerField()),
                ('value', models.IntegerField()),
                ('price', models.IntegerField()),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('value', models.IntegerField()),
                ('price', models.IntegerField()),
                ('chipset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.chipset')),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.manufacturer')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.socket')),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('memory', models.IntegerField()),
                ('value', models.IntegerField()),
                ('price', models.IntegerField()),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('cores', models.IntegerField()),
                ('threads', models.IntegerField()),
                ('frequency', models.FloatField()),
                ('value', models.IntegerField()),
                ('price', models.IntegerField()),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.manufacturer')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.socket')),
            ],
        ),
    ]
