# Generated by Django 3.1.1 on 2020-11-08 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chipset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formfactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ROM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('H', 'HDD'), ('S', 'SSD')], default='H', max_length=1)),
                ('read', models.IntegerField()),
                ('write', models.IntegerField()),
                ('size', models.IntegerField()),
                ('benchmark', models.FloatField()),
                ('price', models.IntegerField()),
                ('url', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.brand')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128)),
                ('frequency', models.IntegerField()),
                ('capacity', models.CharField(max_length=16)),
                ('benchmark', models.FloatField()),
                ('price', models.IntegerField()),
                ('url', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.brand')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.memorytype')),
            ],
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128)),
                ('power', models.IntegerField()),
                ('value', models.IntegerField()),
                ('price', models.IntegerField()),
                ('url', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.brand')),
            ],
        ),
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('url', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.brand')),
                ('chipset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.chipset')),
                ('formfactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.formfactor')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.socket')),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128)),
                ('memory', models.IntegerField()),
                ('benchmark', models.FloatField()),
                ('price', models.IntegerField()),
                ('url', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.brand')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128)),
                ('cores', models.IntegerField()),
                ('threads', models.IntegerField()),
                ('benchmark', models.FloatField()),
                ('frequency', models.IntegerField()),
                ('price', models.IntegerField()),
                ('url', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.brand')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.socket')),
            ],
        ),
    ]
