# Generated by Django 3.1.1 on 2020-10-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rom',
            name='type',
            field=models.CharField(choices=[('H', 'HDD'), ('S', 'SSD')], default='H', max_length=1),
        ),
    ]
