# Generated by Django 3.1.1 on 2020-11-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powersupply',
            name='model',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
