# Generated by Django 3.1.1 on 2020-11-13 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcbcore', '0002_auto_20201113_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powersupply',
            name='url',
        ),
        migrations.RemoveField(
            model_name='powersupply',
            name='value',
        ),
    ]
