# Generated by Django 3.1.1 on 2020-10-29 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcbcore', '0002_rom_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manufacturer',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='manufacture',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='manufacture',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='manufacture',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='powersupply',
            old_name='manufacture',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='manufacture',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='rom',
            old_name='manufacture',
            new_name='brand',
        ),
    ]
