# Generated by Django 3.1.3 on 2020-12-16 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcbcore', '0003_auto_20201114_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='brand',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='pcbcore.brand'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='model',
            field=models.CharField(default='None', max_length=128),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='brand',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='pcbcore.brand'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='model',
            field=models.CharField(default='None', max_length=128),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='brand',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='pcbcore.brand'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='model',
            field=models.CharField(default='None', max_length=128),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='brand',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='pcbcore.brand'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='model',
            field=models.CharField(default='None', max_length=128),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='brand',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='pcbcore.brand'),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='model',
            field=models.CharField(default='None', max_length=128),
        ),
        migrations.AlterField(
            model_name='ram',
            name='brand',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='pcbcore.brand'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='model',
            field=models.CharField(default='None', max_length=128),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='brand',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='pcbcore.brand'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='model',
            field=models.CharField(default='None', max_length=128),
        ),
    ]
