# Generated by Django 3.1.1 on 2020-12-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcbcore', '0004_auto_20201216_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.brand'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='model',
            field=models.CharField(blank=True, default='None', max_length=128),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.brand'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='model',
            field=models.CharField(blank=True, default='None', max_length=128),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.brand'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='model',
            field=models.CharField(blank=True, default='None', max_length=128),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.brand'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='model',
            field=models.CharField(blank=True, default='None', max_length=128),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.brand'),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='model',
            field=models.CharField(blank=True, default='None', max_length=128),
        ),
        migrations.AlterField(
            model_name='ram',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.brand'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='model',
            field=models.CharField(blank=True, default='None', max_length=128),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcbcore.brand'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='model',
            field=models.CharField(blank=True, default='None', max_length=128),
        ),
    ]
