# Generated by Django 3.1.1 on 2020-12-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbcore', '0005_auto_20201224_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='model',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='model',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='model',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='model',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='model',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='ram',
            name='model',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='model',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
